## 3. Обчислити перші 4 головні компоненти для заданої вибірки значень:
  X = {(1,2,5,6,8)
       (5,4,1,2,3)
       (6,5,2,1,3)
       (5,2,4,7,2)
       (2,6,2,8,9)
       (7,8,3,6,2)}

In [9]:
import numpy as np

In [10]:
X = np.array(
    [[5,4,1,2,3],
     [6,5,2,1,3],
     [5,2,4,7,2],
     [2,6,2,8,9],
    [7,8,3,6,2]])

n_components = 4

u, s, vh = np.linalg.svd(X, full_matrices=True)

In [11]:
u

array([[-0.31581508, -0.22129269,  0.29387752,  0.32821111,  0.8106811 ],
       [-0.34853293, -0.40555143,  0.43212534,  0.43691849, -0.58001962],
       [-0.40134093, -0.02272538, -0.81456491,  0.4166538 , -0.03595318],
       [-0.55966693,  0.79016702,  0.23590705, -0.04094851, -0.07127475],
       [-0.55180071, -0.40209107, -0.08795204, -0.72532926,  0.00081592]])

In [12]:
s[n_components:] = 0
np.diag(s)

array([[22.15214442,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  7.35682727,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  5.1696097 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.62572902,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [13]:
vh

array([[-0.4811686 , -0.52279426, -0.24345185, -0.52264418, -0.40340698],
       [-0.66437639, -0.19493526, -0.1018423 ,  0.3944058 ,  0.59554721],
       [-0.029893  ,  0.46789468, -0.36601864, -0.6427042 ,  0.48284846],
       [ 0.45192543, -0.65413475,  0.23261293, -0.25503252,  0.49871914],
       [ 0.34921428, -0.20461842, -0.86155727,  0.30524884, -0.02688705]])

In [14]:
reconst = np.matrix(u) * np.diag(s) * np.matrix(vh)
reconst

matrix([[4.79191126, 4.1219274 , 1.51338213, 1.81810925, 3.01602138],
        [6.14888167, 4.91276436, 1.63268947, 1.13013774, 2.98853715],
        [5.0092286 , 1.9945926 , 3.97723184, 7.00806674, 1.99928946],
        [2.01829508, 5.98928019, 1.95486365, 8.01599176, 8.99859141],
        [6.99979057, 8.00012272, 3.0005167 , 5.99981693, 2.00001612]])

## 2. Лінійні гаусові системи.

Let $$𝐱∈ℝ^{𝐷𝑥}$$ be a hidden variable and $$𝐲∈ℝ^{𝐷𝑦}$$ be a noisy observation of 𝐱. Let us assume we have the following prior and likelihood
$$𝑝(𝐱)=𝒩(𝐱|𝝁_𝑥,𝚺_𝑥 )$$ $$𝑝(𝐲|𝐱)=𝒩(𝐲|𝑨𝒙+𝒃,𝚺_𝑦 )$$
where $$𝑨$$ is a matrix of size $$𝐷_𝑦×𝐷_𝑥$$
Theorem (Bayes rule for linear Gaussian systems): Given a linear Gaussian system, the posterior $$𝑝(𝐱|𝐲)$$ is given by the following:
$$𝑝(𝐱|𝐲)=𝒩(𝐱|𝝁_{𝑥|𝑦},𝚺_{𝑥|𝑦} )$$$$  𝝁_{𝑥|𝑦}=𝚺_{𝑥|𝑦} (𝑨^𝑇 〖𝚺_𝑦〗^{−1} (𝒚−𝒃)+〖𝚺_𝑥〗^{−1} 𝝁_𝑥 ) $$$$〖𝚺_{𝑥|𝑦}〗^{−1}=〖𝚺_𝑥〗^{−1}+𝑨^𝑇 〖𝚺_𝑦〗^{−1} 𝑨$$
The normalization constant 𝑝(𝐲) is given by:
$$𝑝(𝐲)=𝒩(𝐲|𝑨𝝁_𝑥+𝒃,𝚺_𝑦+𝑨^𝑇 𝚺_𝑥 𝑨)$$

## 1. Метод незалежних компонент. Критерії незалежності компонентів.

Метод незалежних компонент - метод відділення багатовимірного сигналу у додатні компоненти без попередніх спостережень або знань про істочник сигналу. ми припускаємо що кожна компонента не є Гаусовим сигналом і кожна статистично незалежна.

Критерії:

    Maximum likelihood estimation: 

$$NLL(V) = \sum_{j=1}^L E(G_j(z_j) \to\min$$where $V=W^-1$ - recognition weights; $z_j≜[𝐯_𝑗]^𝑇𝐱$ and $𝐺_𝑗(𝑧)≜(−log⁡[𝑝_𝑗 (𝑧)] )$

    Maximizing non-Gaussianity – kurtosis or neg-entropy:
$$negentropy(z) ≜ H[N(\mu,\sigma^2)]-H[z] $$

    Minimizing mutual information:
$$I(z)≜𝕂𝕃[𝑝(𝐳)||\prod_j 𝑝(𝑧_𝑗 ) ]=\sum_j H[z_j] -H[z]$$