In [24]:
import numpy as np
from scipy.stats import multivariate_normal, norm

In [32]:
X = np.array([1, 7, 5, 4, 3, 10, 1, 1, 5, 7, 5, 6 ,1])
M = np.zeros((11, 11))

In [33]:
for i in range(X.shape[0] - 1):
    val_1 = X[i]
    val_2 = X[i+1]
    M[val_2][val_1] += 1
    print(val_1, val_2)

1 7
7 5
5 4
4 3
3 10
10 1
1 1
1 5
5 7
7 5
5 6
6 1


In [34]:
M + 1e-10

array([[1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e+00, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e+00, 1.e-10,
        1.e-10, 1.e-10, 1.e+00],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e+00, 1.e-10, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e+00, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e+00, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 2.e+00,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e+00, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e+00, 1.e-10, 1.e-10, 1.e-10, 1.e+00, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10,
        1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10,

In [35]:
def normalize_matrix(matrix):
    row_sums = matrix.sum(axis = 1)
    res = matrix / row_sums[:, np.newaxis]
    return res

In [36]:
print('first iteration')
M

first iteration


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.dot(M, M)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 3., 0., 0., 0., 2., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 1., 2., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.dot(M, np.dot(M, M))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 1., 1., 1., 1., 2., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 3., 0., 0., 0., 2., 1., 0., 0., 0., 1.],
       [0., 5., 0., 1., 0., 1., 3., 4., 0., 0., 3.],
       [0., 3., 0., 0., 0., 2., 1., 0., 0., 0., 1.],
       [0., 4., 0., 1., 0., 3., 2., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])