In [1]:
import numpy as np

In [2]:
x1 = np.array([[1,4,7],[2,8,9]])
x2 = np.array([[1,1,0],[8,10,28]])
x3 = np.array([[0,7,11],[7,5,15]])
x = np.array([1,2.5,7])

In [8]:
a = np.mean(x1,axis=0)

In [9]:
b = np.mean(x2,axis=0)

In [10]:
c = np.mean(x3,axis=0)

In [19]:
cov1 = np.cov(x1)
cov2 = np.cov(x2)
cov3 = np.cov(x3)

In [20]:
a, cov1

(array([1.5, 6. , 8. ]), array([[ 9.        , 10.5       ],
        [10.5       , 14.33333333]]))

In [21]:
b, cov2

(array([ 4.5,  5.5, 14. ]), array([[  0.33333333,  -6.33333333],
        [ -6.33333333, 121.33333333]]))

In [22]:
c, cov3

(array([ 3.5,  6. , 13. ]), array([[31., 19.],
        [19., 28.]]))

In [17]:
print(f'Answer C2 {list(x2)}')

Answer C1 [array([1, 4, 7]), array([2, 8, 9])]


1)y = sum( w_i*x_i+b )for i є N