1. Ансамблеві класифікатори

Моделі що агругують комбінації ваг більш простих моделей f(y|x, $\theta$) = $\sum$ $weights_i * f_m(y|x)$
пу ваги - тренований параметри.
Прикладом ансамблевих методів є 
 - Random Forest
 - Бустингові дерева

Також підвидом ансамблевих моделей можна виділити Stacking, де ми поєднуємо передбачення більш простих моделей для тренування більш складних. 

In [3]:
import numpy as np

In [5]:
X = np.array([[1,2,3,8],
     [5,3,6,2],
     [7,5,6,8],
     [0,0,0,1]])

In [7]:
from sklearn.decomposition import PCA

In [8]:
pca = PCA(n_components=3)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [9]:
print(pca.singular_values_)

[8.96804648 5.53321812 1.48581276]


In [10]:
u, s, vh = np.linalg.svd(X, full_matrices=True)

In [15]:
u[:, :3]

array([[-0.45103945,  0.74955999,  0.47409566],
       [-0.45211097, -0.64452157,  0.60908097],
       [-0.76864884, -0.06716484, -0.63454343],
       [-0.03657932,  0.13505797, -0.04010375]])

In [18]:
vh[:3, :]

array([[-0.47317681, -0.35678615, -0.50741554, -0.62556919],
       [-0.52129636, -0.13642911, -0.35803476,  0.76252759],
       [-0.56857901, -0.24491583,  0.78262522, -0.0650531 ]])

In [19]:
s[:3]

array([17.10171748,  5.64592816,  1.62212023])

In [22]:
reconst = np.matrix(u[:, :3]) * np.diag(s[:3]) * np.matrix(vh[:3, :])

In [23]:
reconst

matrix([[ 1.00650628e+00,  1.98637468e+00,  3.00065557e+00,
          8.00231798e+00],
        [ 4.99374308e+00,  3.01310313e+00,  5.99936955e+00,
          1.99777085e+00],
        [ 7.00293239e+00,  4.99385906e+00,  6.00029547e+00,
          8.00104472e+00],
        [-6.45101869e-02,  1.35096000e-01, -6.50004847e-03,
          9.77017039e-01]])