1.Застосування марківських моделей в задачах моделювання природних мов.

Можемо змоделювати речення у вигляді P(x_1...x_t) = p(x1)*p(x2|x1)*p(x3|x1, x2)* ... *p(xt|x1 ... xt-1). 
Нам потрібно знайти найбільш ймовірну послідовність тегів за даного речення. 
у = argmax P(y|x) = argmax p(x, y)
де P(x, y) = P(x|y)P(y) = Product from t=1 to T P(x_t|y_t)P(y_t|y_t-1) за умови Марківського припущення p(y) = product from t=1 to T P(y_t|y_t-1)


In [16]:
import numpy as np
from scipy.stats import multivariate_normal, norm
x1 = np.array([[1, 3], [2, 4], [3, 5]])
x2 = np.array([[2, 5], [0, 8], [4, 1],[1, 1]])
x3 = np.array([[1, 1], [-5 , 4], [0, 8]])

x_new = np.array([2, 7])

In [17]:
mean_1 = np.mean(x1, axis=0)
mean_2 = np.mean(x1, axis=0)
mean_3 = np.mean(x3, axis=0)

In [18]:
cov_1 = np.cov(x1)
cov_2 = np.cov(x2)
cov_3 = np.cov(x3)

In [20]:
mean_1, cov_1

(array([2., 4.]), array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]))

In [22]:
mean_2, cov_2

(array([2., 4.]), array([[  4.5,  12. ,  -4.5,   0. ],
        [ 12. ,  32. , -12. ,   0. ],
        [ -4.5, -12. ,   4.5,   0. ],
        [  0. ,   0. ,   0. ,   0. ]]))

In [23]:
mean_3, cov_3

(array([-1.33333333,  4.33333333]), array([[ 0. ,  0. ,  0. ],
        [ 0. , 40.5, 36. ],
        [ 0. , 36. , 32. ]]))

Не встигаю доробити, схоже що елемент x_new належить до 1-го класу