Ядерна функція - дійснозначна функція від двох змінних. Зазвичай функція є асиметричною та невідємною, отже може бути інтерпретованою як міра схожості, але не завжди.

Теорема Мерсера: 
якщо матриця Грама є додатньо визначеню, ми можемо порахувати розклад власних векторів як $K = U^{T}\lambdaU $ де $\lambda$ діагональна матриця власних невідємних чисел. 

In [17]:
import numpy as np
from scipy.stats import multivariate_normal, norm

In [18]:
x = np.array([1, 7, 5, 4, 3, 10, 1, 1, 5, 7, 5, 6 ,1])
x

array([ 1,  7,  5,  4,  3, 10,  1,  1,  5,  7,  5,  6,  1])

In [19]:
matrix = np.zeros((11, 11))

In [20]:
for i in range(x.shape[0] - 1):
    val_1 = x[i]
    val_2 = x[i+1]
    matrix[val_2][val_1] += 1
    print(val_1, val_2)

1 7
7 5
5 4
4 3
3 10
10 1
1 1
1 5
5 7
7 5
5 6
6 1


In [29]:
def normalize_matrix(matrix,epsilon=1e-10):
    row_sums = (matrix + epsilon).sum(axis = 1)
    res = matrix / row_sums[:, np.newaxis]
    return res

In [30]:
print('first iteration')
matrix = normalize_matrix(matrix)
matrix

first iteration


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.66666667, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.

In [31]:
print('second iteration')
np.dot(matrix, matrix)

second iteration


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.11111111, 0.        , 0.33333333, 0.        ,
        0.33333333, 0.11111111, 0.        , 0.        , 0.        ,
        0.11111111],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.66666667, 0.        , 0.        ,
        0.        ],
       [0.        , 0.44444444, 0.        , 0.        , 0.        ,
        0.33333333, 0.11111111, 0.        , 0.        , 0.        ,
        0.11111111],
       [0.        , 0.33333333, 0.        , 0.        , 0.

In [33]:
print('third iteration')
res = np.dot(matrix, np.dot(matrix, matrix))
res 

third iteration


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.14814815, 0.        , 0.11111111, 0.33333333,
        0.11111111, 0.03703704, 0.22222222, 0.        , 0.        ,
        0.03703704],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.66666666, 0.        , 0.        ,
        0.        ],
       [0.        , 0.44444444, 0.        , 0.        , 0.        ,
        0.33333333, 0.11111111, 0.        , 0.        , 0.        ,
        0.11111111],
       [0.        , 0.25925926, 0.        , 0.11111111, 0.        ,
        0.11111111, 0.14814815, 0.22222222, 0.        , 0.        ,
        0.14814815],
       [0.        , 0.44444444, 0.        , 0.        , 0.